version: 2

jobs:
  build:api:
    docker:
      - image: cimg/base:2020.01
    
    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push api image
          command: |
            docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN
            docker pull $IMAGE:api || true
            docker build \
            --cache-from $IMAGE:api \
            --tag $IMAGE:api  \
            --file ./services/trivia/Dockerfile.prod \
            "./services/trivia"
            docker push $IMAGE:trivia

  build:client:
    docker:
      - image: cimg/base:2020.01

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push client image
          command: |
            docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN
            docker pull $IMAGE:client || true
            docker build \
            --cache-from $IMAGE:client \
            --tag $IMAGE:client  \
            --file ./services/client/Dockerfile.ci \
            "./services/client"
            docker push $IMAGE:client

  test:client:
    docker:
      - image: $IMAGE:client
    
    steps:
      - run: 
          name: Lint and test client
          command: |
            cd /usr/src/app
            npm run prettier:check
            npm run lint
            npm run test
  
workflows:
  version: 2
  build-test:
    jobs:
      - build:client
      - test:client:
          requires:
            - build:client
      - build:api